### ISSUE TITLE
installing and running npm test fails.

### ISSUE THREAD

**Issue by reduxdj** [chenckang/node-stylus-require#8]
2 failing

  1) node ->register:
     TypeError: Path must be a string. Received undefined
      at assertPath (path.js:7:11)
      at Object.dirname (path.js:1324:5)
      at Array.<anonymous> (/Users/patricklemiuex/node-stylus-require/index.js:29:14)
      at Renderer.render (/Users/patricklemiuex/node-stylus-require/node_modules/stylus/lib/renderer.js:114:27)
      at Function.exports.render (/Users/patricklemiuex/node-stylus-require/node_modules/stylus/lib/stylus.js:82:37)
      at Object.require.extensions.(anonymous function) [as .styl] (/Users/patricklemiuex/node-stylus-require/index.js:24:12)
      at require (internal/module.js:20:19)
      at Context.<anonymous> (node/node.js:9:730)

  2) express ->intercept:
     TypeError: Path must be a string. Received undefined

**Comment by chenckang** [comment]
I check the test cases again and find everything is ok on Mac OS X 10.11.1.

And additionally, test cases on travis-ci are also passed, here is the location - https://travis-ci.org/chenckang/node-stylus-require.

Some tips:
1.  Try to remove node_modules and run it again.
2.  The error is caused by passing an undefined argument to node path module of the stylus npm package.

If you have more information, you will always be welcome to feed back.
